### ISSUE TITLE
add_library cannot create imported target "glog::glog" because another target with the same name already exists.

### ISSUE THREAD

**Issue by belkahorry** [cvg/pyceres#8]
Hi, i've installed Ceres,Colmap,and met this error: 
```
pip install -e .
× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [145 lines of output]
    running develop
    /home/xxx/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /home/xxx/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running egg_info
    writing pyceres.egg-info/PKG-INFO
    writing dependency_links to pyceres.egg-info/dependency_links.txt
    writing requirements to pyceres.egg-info/requires.txt
    writing top-level names to pyceres.egg-info/top_level.txt
    reading manifest file 'pyceres.egg-info/SOURCES.txt'
    writing manifest file 'pyceres.egg-info/SOURCES.txt'
    running build_ext
    -- Found METIS: /usr/include (found suitable version "5.1.0", minimum required is "5.1.0")
    -- Found AMD headers in: /usr/include/suitesparse
    -- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
    -- Found CAMD headers in: /usr/include/suitesparse
    -- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
    -- Found CCOLAMD headers in: /usr/include/suitesparse
    -- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
    -- Found CHOLMOD headers in: /usr/include/suitesparse
    -- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
    -- Found COLAMD headers in: /usr/include/suitesparse
    -- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
    -- Found SPQR headers in: /usr/include/suitesparse
    -- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
    -- Found Config headers in: /usr/include/suitesparse
    -- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
    -- Found Intel Thread Building Blocks (TBB) library (2020.1 / 11101) include location: . Assuming SuiteSparseQR was compiled with TBB.
    -- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
    -- Found METIS: /usr/include (found version "5.1.0")
    -- Found required Ceres dependency: Eigen version 3.4.0 in /usr/local/share/eigen3/cmake
    -- Found required Ceres dependency: glog
    -- Found required Ceres dependency: gflags
    -- Found Ceres version: 2.2.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, SchurSpecializations, Multithreading]
    -- Found METIS: /usr/include (found suitable version "5.1.0", minimum required is "5.1.0")
    -- Found AMD headers in: /usr/include/suitesparse
    -- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
    -- Found CAMD headers in: /usr/include/suitesparse
    -- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
    -- Found CCOLAMD headers in: /usr/include/suitesparse
    -- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
    -- Found CHOLMOD headers in: /usr/include/suitesparse
    -- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
    -- Found COLAMD headers in: /usr/include/suitesparse
    -- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
    -- Found SPQR headers in: /usr/include/suitesparse
    -- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
    -- Found Config headers in: /usr/include/suitesparse
    -- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
    -- Found Intel Thread Building Blocks (TBB) library (2020.1 / 11101) include location: . Assuming SuiteSparseQR was compiled with TBB.
    -- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
    -- Found METIS: /usr/include (found version "5.1.0")
    -- Found required Ceres dependency: Eigen version 3.4.0 in /usr/local/share/eigen3/cmake
    CMake Error at /usr/local/lib/cmake/Ceres/FindGlog.cmake:349 (add_library):
      add_library cannot create imported target "glog::glog" because another
      target with the same name already exists.
    Call Stack (most recent call first):
      /usr/local/lib/cmake/Ceres/CeresConfig.cmake:248 (find_package)
      /usr/local/share/colmap/COLMAPConfig.cmake:92 (find_package)
      CMakeLists.txt:14 (find_package)
    
    
    -- Found required Ceres dependency: glog
    -- Found required Ceres dependency: gflags
    -- Found Ceres version: 2.2.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, SchurSpecializations, Multithreading]
    -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: program_options filesystem system unit_test_framework
    -- Found Eigen
    --   Includes : /usr/local/include/eigen3
    -- Found FreeImage
    --   Includes : /usr/include
    --   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
    -- Found Glog
    --   Includes : /usr/include
    --   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
    CMake Warning (dev) at /usr/local/share/cmake-3.21/Modules/FindOpenGL.cmake:315 (message):
      Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
      available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
      cmake_policy command to set the policy and suppress this warning.
    
      FindOpenGL found both a legacy GL library:
    
        OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so
    
      and GLVND libraries for OpenGL and GLX:
    
        OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
        OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so
    
      OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
      compatibility with CMake 3.10 and below the legacy GL library will be used.
    Call Stack (most recent call first):
      /usr/local/share/colmap/COLMAPConfig.cmake:109 (find_package)
      CMakeLists.txt:14 (find_package)
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Found Glew
    --   Includes : /usr/include
    --   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
    -- Using header-only CGAL
    -- Targetting Unix Makefiles
    -- Using /usr/bin/c++ compiler.
    -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")
    -- Boost include dirs: /usr/include
    -- Boost libraries:
    -- Using gcc version 4 or later. Adding -frounding-math
    -- pybind11 v2.8.1
    -- Configuring incomplete, errors occurred!
    See also "/home/xxx/pyceres/build/temp.linux-x86_64-cpython-39/CMakeFiles/CMakeOutput.log".
    See also "/home/xxx/pyceres/build/temp.linux-x86_64-cpython-39/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/xxx/pyceres/setup.py", line 80, in <module>
        setup(
      File "/home/xxx/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/xxx/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/xxx/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/xxx/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
        self.run_command(cmd)
      File "/home/xxx/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/home/xxx/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
        cmd_obj.run()
      File "/home/xxx/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/xxx/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/xxx/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
        self.distribution.run_command(command)
      File "/home/xxx/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/home/xxx/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
        cmd_obj.run()
      File "/home/xxx/pyceres/setup.py", line 34, in run
        self.build_extension(ext)
      File "/home/xxx/pyceres/setup.py", line 76, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/home/xxx/anaconda3/envs/torch/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/home/xxx/pyceres', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/xxx/pyceres', '-DPYTHON_EXECUTABLE=/home/xxx/anaconda3/envs/torch/bin/python', '-DVERSION_INFO=0.0.0', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ['cmake', '/home/xxx/pyceres', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/xxx/pyceres', '-DPYTHON_EXECUTABLE=/home/xxx/anaconda3/envs/torch/bin/python', '-DVERSION_INFO=0.0.0', '-DCMAKE_BUILD_TYPE=Release']
    [end of output]
```

Enviroment：
Ubuntu20.04 
cmake 3.21.6
gcc 9.4.0(out of conda)
gcc 12.2.0(conda)

**Comment by Skydes** [comment]
Can you share the commit hashes for COLMAP and Ceres?

**Comment by belkahorry** [comment]
> Can you share the commit hashes for COLMAP and Ceres?
COLMAP: b016aed098d85be27fb1597da4de88b3743b9777 
Ceres: 9aa52c6ff74358d1b91542221e0545bb61bdedcc
Both were pulled and built yesterday.

**Comment by Phil26AT** [comment]
Could you please check if PR #10 fixes your issue? I assume the double ceres load (explicit and via COLMAP) was the issue.

**Comment by belkahorry** [comment]
It works, thanks a lot.Colmap have already found Ceres before.
